-- 1. Create the `products` table
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  nome_completo TEXT,
  categoria TEXT NOT NULL,
  estoque INT NOT NULL DEFAULT 0,
  preco_unitario NUMERIC NOT NULL,
  preco_embalagem NUMERIC NOT NULL,
  unidade TEXT NOT NULL,
  icon TEXT DEFAULT 'Package',
  imagens JSONB DEFAULT '[]'::jsonb
);

-- If your products table already exists, run this migration safely:
ALTER TABLE products ADD COLUMN IF NOT EXISTS estoque INT NOT NULL DEFAULT 0;

-- 2. Create the `category_images` table
CREATE TABLE category_images (
  categoria TEXT PRIMARY KEY,
  image_url TEXT NOT NULL
);

-- 3. Create the `store_info` table (we'll insert one row)
CREATE TABLE store_info (
  id INT PRIMARY KEY DEFAULT 1,
  empresa TEXT,
  whatsapp TEXT
);

-- 4. Set liberal Row Level Security (RLS) policies so the frontend can read/write without complex auth initially
-- (we can lock this down later with the admin password)
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE category_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE store_info ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anon read/write products" ON products FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon read/write category_images" ON category_images FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon read/write store_info" ON store_info FOR ALL TO public USING (true) WITH CHECK (true);

-- 5. Create the Storage Bucket for images
INSERT INTO storage.buckets (id, name, public) VALUES ('images', 'images', true);

-- Enable RLS on storage objects and allow public read/write
CREATE POLICY "Allow anon read/write objects" ON storage.objects FOR ALL TO public USING (bucket_id = 'images') WITH CHECK (bucket_id = 'images');
